/* kat_tempest.h — Known-Answer Tests for Tempest v3 (GF(2)-only)
 *
 * Test vector: key={1,2,3,4}, nonce={5,6}, first 10 outputs
 * Phase A: XOR + constant K (pure GF(2), no carries)
 * Phase C: 4-level cross-word AND cascade + dual Pre-mix (deg ×16/round)
 * Phase A(lin): snapshot ANDs for linear resistance
 * Security: a_min >= 7, DP(r) <= 2^{-7r} (MILP-verified)
 *
 * Generated by gen_kat_tempest; regenerate if round function changes.
 */
#ifndef KAT_TEMPEST_H
#define KAT_TEMPEST_H

#include "tempest_v3.h"

#define KAT_TEMPEST_COUNT 10

static const uint64_t kat_tempest_expected[KAT_TEMPEST_COUNT] = {
    0x6BBE30BB1D12DDD0ULL,
    0xB9167FE6CCEC68D9ULL,
    0xCF6F7BA5C6AED360ULL,
    0xA53C77D6D081BEC3ULL,
    0x7F5A13D9CBF1CD84ULL,
    0x7B642126FA3B4609ULL,
    0x6AE3C72B55FF5B19ULL,
    0xB2CDDDB1B2B9DDA1ULL,
    0xD71A44CD824527D2ULL,
    0x9AF63FB79C533F3EULL,
};

static inline int tempest_kat_verify(tx4_state *s) {
    uint64_t key[4] = {1, 2, 3, 4};
    uint64_t nonce[2] = {5, 6};
    tx5cmul_init(s, key, nonce);
    for (int i = 0; i < KAT_TEMPEST_COUNT; i++) {
        uint64_t got = tx5cmul_next(s);
        if (got != kat_tempest_expected[i]) {
            return -1;
        }
    }
    return 0;
}

#endif /* KAT_TEMPEST_H */
