/* kat_tempest.h — Known-Answer Tests for Tempest v3 (GF(2)-only)
 *
 * Test vector: key={1,2,3,4}, nonce={5,6}, first 10 outputs
 * Phase B: XOR + constant K (pure GF(2), no carries)
 * Phase C: 4-level cross-word AND cascade + dual Pre-mix (deg ×16/round)
 * Phase B(lin): snapshot ANDs for linear resistance
 * Security: a_min >= 7, DP(r) <= 2^{-7r} (MILP-verified)
 *
 * Generated by gen_kat_tempest; regenerate if round function changes.
 */
#ifndef KAT_TEMPEST_H
#define KAT_TEMPEST_H

#include "tempest_v3.h"

#define KAT_TEMPEST_COUNT 10

static const uint64_t kat_tempest_expected[KAT_TEMPEST_COUNT] = {
    0x471FA748639BAAF5ULL,
    0x0C9CFD891C696092ULL,
    0x742B84F454567DD8ULL,
    0x8A1E7F82DDFE940EULL,
    0xADCED0C93D0BDEC0ULL,
    0x26FCD4586874AAD1ULL,
    0x99C81CE660F81414ULL,
    0x95DF858CCB86C8CDULL,
    0xABAF7128861B7EEDULL,
    0x8331E06AE51EC63BULL,
};

static inline int tempest_kat_verify(tx4_state *s) {
    uint64_t key[4] = {1, 2, 3, 4};
    uint64_t nonce[2] = {5, 6};
    tx5cmul_init(s, key, nonce);
    for (int i = 0; i < KAT_TEMPEST_COUNT; i++) {
        uint64_t got = tx5cmul_next(s);
        if (got != kat_tempest_expected[i]) {
            return -1;
        }
    }
    return 0;
}

#endif /* KAT_TEMPEST_H */
