#!/usr/bin/env python3
"""gen_dimacs.py --- 生成 Tempest v3 DIMACS CNF 文件
供 CaDiCaL/Kissat/CryptoMiniSat 等标准 SAT 求解器使用。

生成的是"密钥恢复 CNF": 已知 R 轮后的输出比特,
求解器寻找满足约束的输入密钥。

用法:
  python gen_dimacs.py [W] [R] > tempest.cnf
  kissat tempest.cnf

依赖: 无 (纯 Python, 使用标准 DIMACS 格式)
"""
import sys

W = 64
R = 1
if len(sys.argv) > 1:
    W = int(sys.argv[1])
if len(sys.argv) > 2:
    R = int(sys.argv[2])

# CNF 构建
next_var = 1
clauses = []
comments = []


def fresh():
    global next_var
    v = next_var
    next_var += 1
    return v


def clause(*lits):
    clauses.append(list(lits))


def emit_and(a, b, out):
    """AND(a,b)=out: (¬out∨a)(¬out∨b)(¬a∨¬b∨out)"""
    clause(-out, a)
    clause(-out, b)
    clause(-a, -b, out)


def emit_xor(a, b, out):
    """XOR(a,b)=out"""
    clause(-out, -a, -b)
    clause(-out, a, b)
    clause(out, -a, b)
    clause(out, a, -b)


class Word:
    def __init__(self, bits):
        self.bits = list(bits)

    @classmethod
    def new(cls, nbits):
        return cls([fresh() for _ in range(nbits)])

    @classmethod
    def zero(cls, nbits):
        return cls([0] * nbits)

    def copy(self):
        return Word(self.bits[:])

    def rotl(self, r, nbits):
        r = r % nbits
        return Word([self.bits[(i - r) % nbits] for i in range(nbits)])

    def xor(self, other, nbits):
        dst = [0] * nbits
        for i in range(nbits):
            a, b = self.bits[i], other.bits[i]
            if a == 0:
                dst[i] = b
            elif b == 0:
                dst[i] = a
            elif a == -b:
                dst[i] = 0
            else:
                v = fresh()
                emit_xor(a, b, v)
                dst[i] = v
        return Word(dst)

    def xor3(self, a, b, nbits):
        """self XOR a XOR b"""
        t = self.xor(a, nbits)
        return t.xor(b, nbits)

    def and_word(self, other, nbits):
        dst = [0] * nbits
        for i in range(nbits):
            a, b = self.bits[i], other.bits[i]
            if a == 0 or b == 0:
                dst[i] = 0
            elif a == b:
                dst[i] = a
            else:
                v = fresh()
                emit_and(a, b, v)
                dst[i] = v
        return Word(dst)


def andmix4(t, nbits):
    """4-stage AND-mix cascade"""
    rots = [(31, 53), (17, 43), (7, 23), (5, 19)]
    cur = t.copy()
    for r1, r2 in rots:
        tr1 = cur.rotl(r1, nbits)
        tr2 = cur.rotl(r2, nbits)
        a = tr1.and_word(tr2, nbits)  # rotl(t,r1) & rotl(t,r2)
        cur = cur.xor(a, nbits)
    return cur


def premix_andmix4(t, nbits):
    """pre-mix (22,26) + andmix4"""
    t = t.xor(t.rotl(22, nbits).xor(t.rotl(26, nbits), nbits), nbits)
    return andmix4(t, nbits)

def tempest_round(u, v, w, z, nbits):
    """One round: Phase B (enhanced 4-source) + C (4-word) + D (cross-word)"""
    u0, v0, w0, z0 = u.copy(), v.copy(), w.copy(), z.copy()

    # Phase B: 4-source XOR-ROT
    u1 = u0.xor3(v0.rotl(7, nbits), w0.rotl(17, nbits), nbits).xor(z0.rotl(23, nbits), nbits)
    v1 = v0.xor3(w0.rotl(11, nbits), z0.rotl(13, nbits), nbits).xor(u0.rotl(19, nbits), nbits)
    w1 = w0.xor3(z0.rotl(13, nbits), u0.rotl(31, nbits), nbits).xor(v0.rotl(11, nbits), nbits)
    z1 = z0.xor3(u0.rotl(17, nbits), v0.rotl(7, nbits), nbits).xor(w0.rotl(13, nbits), nbits)

    # Phase C: pre-mix + 4-word andmix4
    u2 = premix_andmix4(u1, nbits) if nbits >= 4 else u1
    v2 = premix_andmix4(v1, nbits) if nbits >= 4 else v1
    w2 = premix_andmix4(w1, nbits) if nbits >= 4 else w1
    z2 = premix_andmix4(z1, nbits) if nbits >= 4 else z1

    # Phase D: cross-word mixing
    u3 = u2.xor(v2.rotl(3, nbits).xor(w2.rotl(7, nbits), nbits), nbits)
    v3 = v2.xor(w2.rotl(5, nbits).xor(z2.rotl(11, nbits), nbits), nbits)
    w3 = w2.xor(z2.rotl(7, nbits).xor(u2.rotl(13, nbits), nbits), nbits)
    z3 = z2.xor(u2.rotl(11, nbits).xor(v2.rotl(17, nbits), nbits), nbits)

    return u3, v3, w3, z3


def generate_cnf(W, R):
    """Generate key-recovery CNF"""
    comments.append(f"c Tempest v3 Key Recovery CNF")
    comments.append(f"c W={W}, R={R}")
    comments.append(f"c Generated by gen_dimacs.py")
    comments.append(f"c Encoding: AND/XOR with Tseitin")

    # Key variables
    u = Word.new(W)
    v = Word.new(W)
    w = Word.new(W)
    z = Word.new(W)

    cur_u, cur_v, cur_w, cur_z = u, v, w, z

    for rnd in range(R):
        cur_u, cur_v, cur_w, cur_z = tempest_round(
            cur_u, cur_v, cur_w, cur_z, W)
        comments.append(f"c Round {rnd + 1} complete")

    # Full output function: fold4 → linear self-diff → andmix4 → whitener
    out = cur_u.xor3(cur_v.rotl(32, W),
                     cur_w.xor(cur_z.rotl(16, W), W), W)
    # t ^= rotl(t, 27) ^ rotl(t, 17)
    out = out.xor(out.rotl(27, W).xor(out.rotl(17, W), W), W)
    # andmix4
    out_mixed = andmix4(out, W)
    # t ^= t >> 32 (whitener)
    # Only need upper 32 bits; lower 32 are XOR'd
    # For SAT: out_mixed[i+32] XOR out_mixed[i] for i in 0..31
    whitened = out_mixed.copy()
    for i in range(W):
        shifted_idx = i + 32
        if shifted_idx < W:
            v = fresh()
            emit_xor(out_mixed.bits[i], out_mixed.bits[shifted_idx], v)
            whitened.bits[i] = v
    # Output bits are whitened[0..W-1]
    comment_lines = "\n".join(comments) + "\n"

    # Write DIMACS
    total_vars = next_var - 1
    output = comment_lines
    output += f"p cnf {total_vars} {len(clauses)}\n"

    # Write variable name mapping for debugging
    output += "c Variable mapping (var=1..W*4 for key bits):\n"

    for c in clauses:
        output += " ".join(str(l) for l in c) + " 0\n"

    return output


if __name__ == '__main__':
    output = generate_cnf(W, R)
    sys.stdout.write(output)
    sys.stderr.write(f"CNF stats: {next_var - 1} vars, {len(clauses)} clauses\n")
